### ISSUE TITLE
Updated Broccoli API

### ISSUE THREAD

**Issue by kylecordes** [statianzo/broccoli-ng-templatecache#1]
How about an update to use the newer broccoli API?

"The .read/.rebuild API is no longer supported as of Broccoli 1.0. Plugins must now derive from broccoli-plugin. https://github.com/broccolijs/broccoli/blob/master/docs/broccoli-1-0-plugin-api.md"

**Comment by statianzo** [comment]
If you put together a pull request, I'll get it merged and publish a new release.

**Comment by kylecordes** [comment]
Here you go:

https://github.com/statianzo/broccoli-ng-templatecache/pull/2

**Comment by statianzo** [comment]
PR merged and `0.2.0` released. Thanks for the help!
